# -*- coding: utf-8 -*-
"""Lecture2_MovieExplorer_DataTypes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MedJ8ptoh6-C3xtd3tZay2GTBWUmz8zm

# 🎬 Lecture 1 Notebook — *Movie Explorer: Data Types*

## 📖 Introduction to Data Types
Python has a few **basic data types** we’ll use today:  

- **Integers (`int`)**: whole numbers like vote counts  
- **Floats (`float`)**: decimal numbers like ratings  
- **Booleans (`bool`)**: `True` or `False` values like trailer availability  
- **Strings (`str`)**: text like movie titles and overviews  

We’ll use real movie data from TMDb to practice each one.    

Today only you will use my account to grab the data.  The last thing you should do today is get your own account.

If you have your own account, you can update the key right now.


**I will be deleting this key after lecture, so if you want to run this later you will need to use your own key**

## 🎬 Provided Movie Data
"""

import requests
import json

YOUR_KEY = "7894b8293488ef9fa487f7977869d732"

def get_movie(title):
    url = f"https://api.themoviedb.org/3/search/movie?query={title}&api_key={YOUR_KEY}"
    print(url)
    r = requests.get(url).json()
    return r["results"][0]

movie = get_movie("Inception")
print(json.dumps(movie, indent=4)) # Look at the raw data

"""## 1️⃣ Integers (`int`)

Integers are whole numbers. Example fields:  
- `id`: the movie’s unique ID  
- `vote_count`: how many people rated the movie
"""

movie_id = movie["id"]
vote_count = movie["vote_count"]

# Use comma printing for ints
print("Movie ID is", movie_id)
print("This movie has", vote_count, "votes.")





#print(f"This movie has {vote_count:,} votes.")

"""### Example: Updating an Integer"""

vote_count = vote_count + 500
print("The vote count has been updated.  The total is", vote_count)

"""
### 📝 Challenges — Integers
1. Print the `vote_count` again in your own sentence.  
2. Add 1000 to the vote count and print the new total.  
"""

# ✍️ Student code here

"""## 2️⃣ Floats (`float`)

Floats are numbers with decimals. Example fields:  
- `vote_average`: average rating (e.g., 8.8)  
- `popularity`: popularity score
"""

rating = float(movie["vote_average"])
popularity = float(movie["popularity"])

# Try concatenation with + (this will cause an error!)
print("Rating is " + rating)    # 🚨 TypeError here


# We will look at a solution below.

"""## 🔄 Type Conversion Functions

We can convert between types using functions like:  
- `str()` → to string  
- `int()` → to integer  
- `float()` → to float  
- `bool()` → to boolean
"""

# Now it works after conversion
print("Rating is " + str(rating))
print("Popularity score is " + str(popularity))




# print(f"Popularity score is {popularity:.1f}")
# print(f"Popularity score is {popularity:.4f}")

"""
### 📝 Challenges — Floats
1. Multiply the rating by 10 and print: `"Rating out of 100: XX"`.  
2. Print popularity in a sentence.  
"""

# ✍️ Student code here

"""## 3️⃣ Booleans (`bool`)

Booleans are either `True` or `False`. Example fields:  
- `video`: does the movie have an associated trailer?  
- `adult`: is the movie marked as adult content?
"""

video = bool(movie["video"])
adult = bool(movie["adult"])

# Use f-strings for printing
print(f"Has a video? {video}")
print(f"Adult content? {adult}")

"""
### 📝 Challenges — Booleans

1. Print `"Trailer available:"` followed by the actual `video` value.  
2. Print `"Adult movie:"` followed by the `adult` value.  
"""

# ✍️ Student code here

"""### ⚡ Extra: How Booleans Work in Python

Almost everything in Python converts to `True` when turned into a Boolean:  

- **False values**: `0`, `0.0`, `""` (empty string), `[]` (empty list), `{}` (empty dict), and `None`.  
- **Everything else** is `True`.
"""

print(bool(0))         # False
print(bool(5))         # True
print(bool(""))        # False
print(bool("Hello"))   # True
print(bool([]))        # False
print(bool([1, 2]))    # True

"""*Boolean values in Python vs other programming languages*.

You may have noticed that the data we grabbed from the web used true/false instead of True/False.  In Python you must use the capital letters.

## 4️⃣ Strings (`str`)

Strings are text, like titles and overviews. You can use different quotes depending on the text:
"""

title1 = "Schindler's List"         # needs double quotes because of '
title2 = 'He said, "I’ll be back."' # needs single quotes because of "
title3 = """This is
a multi-line string
for long overviews."""

print(title1)
print(title2)
print(title3)

"""
### 📝 Challenges — Strings
1. Print the `title` of the movie in a sentence.  
2. Print the `overview`.  

"""

# ✍️ Student code here --
# Go back up to find how to get the title and overview data.

"""## 🎬 Your Turn: Try Another Movie!

Let’s explore a different movie.
"""

# Example: fetch Titanic
movie2 = get_movie("Titanic")
print(json.dumps(movie2, indent=4)) # Look at the raw data

"""
### 📝 Final Challenge
Using what you’ve learned, print out:  
1. The movie’s ID (`int`).  
2. Its rating (`float`).  
3. Whether it has a video (`bool`).  
4. Its title (`str`).  
"""

# ✍️ Student code here

"""## 🔑 Your Own API Key and Movie

Now it’s time to try the API with **your own account**.  

1. Go to [The Movie Database API page](https://www.themoviedb.org/documentation/api) and sign up for a free API key.
2.  You will need to verify the account from your email.  
3. Log in.   
4. Go to your profile --> API Subscription --> Access your API key
5. When prompted for a URL just use "**https://si.umich.edu/**".  When prompted for a reason you can use "**I will be using this for my homework in SI101**
"
6. Copy the key into the variable `my_key`.  
7. . Pick **any movie you like** and assign the name to `my_movie`.
"""

# ✍️ Student code here
YOUR_KEY =  "rhhjgfdbffmj.lkhgfdf"      # update with your actual key - what type should it be?
your_movie = "Pinochio"     # update with any movie you like - what type should it be?

"""### Call the API With Your Own Info

Run the code below.  Try changing the movie name above and run **both cells** again.
"""

def get_movie(title):
    url = f"https://api.themoviedb.org/3/search/movie?query={title}&api_key={YOUR_KEY}"
    print(url)
    r = requests.get(url).json()
    return r["results"][0]

movie3 = get_movie(your_movie)
print(json.dumps(movie, indent=4)) # Look at the raw data

# Print some info about your chosen movie
print("Your movie is:", movie3["title"])
print("ID:", movie3["id"])
print("Rating:", movie3["vote_average"])
print("Has video?", movie3["video"])

"""
## ✅ Wrap-Up
Today we:  
- Explored **ints, floats, bools, and strings**.  
- Practiced **printing** in different styles.  
- Learned about **type conversion**.  
- Saw that almost everything converts to `True`.  
- Practiced with **two movies**, then set up your **own key** and chose a movie yourself.  

Next time, we’ll use **lists and dictionaries** to handle bigger groups of movie data.  


## ✅ Deliverable.  
Take a screenshot of the output of the cell above.  Submit it Canvas where I have a sample screenshot.
"""